root_obs: &root_obs s3://bucket-3690/ZhouPeng

network_pkl: &network_pkl
  carla_r256_32_ks1_v1: "../bucket_3690/results/StyleSDF-exp/train_cips3d_carla_v3/train_r256_r32_ks1-20220421_155851_633/ckptdir/resume"
  carla_r256_32_ks3_v1: "../bucket_3690/results/StyleSDF-exp/train_cips3d_carla_v3/train_r256_r32_ks1-20220421_160157_608/ckptdir/resume"
  carla_r256_64_ks1: "../bucket_3690/results/StyleSDF-exp/train_cips3d_carla_v3/train_r256_r64_ks1-20220418_130144_474/ckptdir/resume"
  carla_r512_64_ks3: "../bucket_3690/results/StyleSDF-exp/train_cips3d_carla_v3/train_r512_r64_ks1-20220418_110053_505/ckptdir/resume"
  carla_r256_64_ks3: "../bucket_3690/results/StyleSDF-exp/train_cips3d_carla_v3/train_r256_r64_ks1-20220418_095959_852/ckptdir/resume"
#  carla_r256_64_ks3: "../bucket_3690/results/StyleSDF-exp/train_cips3d_carla_v3/train_r256_r64_ks1-20220417_153230_757/ckptdir/resume"
  carla_r256_32_ks3: "../bucket_3690/results/StyleSDF-exp/train_cips3d_carla_v3/train_r256_r32_ks1-20220415_161035_594/ckptdir/resume"


obs_inception_v3: &obs_inception_v3
  datapath_obs: 'keras/cache/torch/hub/checkpoints/weights-inception-2015-12-05-6726825d.pth'
  datapath: "~/.cache/torch/hub/checkpoints/weights-inception-2015-12-05-6726825d.pth"
  disable: false
  overwrite: false
  unzip: false

obs_carla_r256: &obs_carla_r256
  datapath_obs: 'keras/carla/carla_lmdb_256/'
  datapath: "datasets/carla/carla_lmdb_256/"
  disable: false
  overwrite: false
  unzip: false

obs_carla_r512: &obs_carla_r512
  datapath_obs: 'keras/carla/images_lmdb_512/'
  datapath: "datasets/carla/images_lmdb_512/"
  disable: false
  overwrite: false
  unzip: false

G_cfg: &G_cfg
  register_modules:
    - "exp.cips3d.models.model_v3"
  name: "exp.cips3d.models.model_v3.Generator"
  enable_decoder: true
  freeze_renderer: false
  renderer_detach: true
  predict_rgb_residual: false
  scale_factor: 1
  renderer_cfg:
#    N_layers_renderer: 8
    N_layers_renderer: 2
    input_dim: 3
    hidden_dim: 256
#    style_dim: 256
    view_dim: 3
    with_sdf: true
    output_features : true
  mapping_renderer_cfg:
    z_dim: 256
    style_dim: 256
    N_layers: 3
  decoder_cfg:
    size_start: 4
    size_end: 1024
#    'style_dim': 512
#    'in_channel': 256
    'channel_multiplier': 2
    'project_noise': False
    'upsample_list': [128, 256, 512, 1024]
#    'upsample_list': []
    'kernel_size': 1
  mapping_decoder_cfg:
#    z_dim: 256
    style_dim: 512
    lr_mul_mapping: 0.01
    N_layers: 5


G_kwargs: &G_kwargs
  cam_cfg:
    'img_size': 64
#    'uniform': False
#    'azim_range': 0.3
#    'elev_range': 0.15
    'uniform': True
    'azim_range': [-3.14, 3.14]
    'elev_range': [0.1, 1.57]
    'fov_ang': 15
    'dist_radius': 0.3
  nerf_cfg:
#    N_samples: 24
    N_samples: 48
    perturb: true
    static_viewdirs: false

_build_generator:
  G_cfg: *G_cfg
  G_kwargs: *G_kwargs

D_cfg: &D_cfg
  register_modules:
    - "exp.cips3d.models.discriminator"
  name: "exp.cips3d.models.discriminator.D_StyleGAN_Progressive"
  input_size: 1024
  channel_multiplier: 2
  pretrained_size: null

D_renderer_cfg: &D_renderer_cfg
  register_modules:
    - "exp.cips3d.models.discriminator_pose"
  name: "exp.cips3d.models.discriminator_pose.D_VolumeRender_Progressive"
  input_size: 1024
  viewpoint_loss: true
  pretrained_size: null

train_base:
  root_obs: *root_obs
  obs_training_dataset: *obs_carla_r256
#  obs_training_dataset: *obs_ffhq_r64
  obs_inception_v3: *obs_inception_v3
  G_cfg: *G_cfg
  G_kwargs: *G_kwargs
  D_cfg: *D_cfg
  D_renderer_cfg: *D_renderer_cfg
  # optims
  G_lr_render: 2.e-5
  G_lr_decoder: 0.002
  D_lr_render: 2.e-4
  D_lr_decoder: 0.002
  # args
  total_iters: 200000
  ema_start: 1000
  batch: 4
  chunk: 4
  expname: ffhq1024x1024
  size: 1024
  tl_finetune: false
  finetune_dir: "results/StyleSDF-exp/train_volume_render_ffhq/train_volume_render-20220325_102346_871/ckptdir/01"
  # train
  d_reg_every: 15
  g_reg_every: 5
#  d_reg_every: 16
#  g_reg_every: 4
  path_regularize: 2
  N_rays_forward: null
  N_rays_grad: null
  N_samples_forward: null
  fade_D: true
  fade_steps: 10000
  init_renderer: true
  init_renderer_ckpt: null
#  init_renderer_ckpt: "results/StyleSDF-exp/train_cips3d_ffhq/train_r64-20220331_224622_038/ckptdir/G_sdf_init.pth"
  grad_clip: 20.
  warmup_iters: -1
  num_workers: 0
  # loss
  lambda_gp: 10.
  lambda_pose: 15.
  lambda_eikonal: 0.1
  lambda_min_surf: 0.05
  min_surf_beta: 100.
  # log
  log_txt_every: 10
  log_ckpt_every: 500
  log_N_row: 8
  log_N_col: 8
  # eval
  batch_gpu: 4
  N_gen_images_eval: 2048
  N_real_images_eval: 2048
  del_fid_real_images: true
  kid: false


train_r256_r32_ks1:
  base: train_base
  obs_training_dataset: *obs_carla_r256
  G_cfg:
    enable_decoder: true
#    freeze_renderer: true
#    renderer_detach: true
    freeze_renderer: false
    renderer_detach: false
    predict_rgb_residual: false
    renderer_cfg:
      N_layers_renderer: 2
      hidden_dim: 256
    decoder_cfg:
      upsample_list: [128, 256, 512]
      kernel_size: 1
  G_kwargs:
    cam_cfg:
      img_size: 32
  D_cfg:
    pretrained_size: null
  D_renderer_cfg:
    pretrained_size: null
  init_renderer: true
  init_iters: 20000
  tl_finetune: false
#  finetune_dir: "../bucket_3690/results/StyleSDF-exp/train_cips3d_ffhq_v3/train_r64-20220411_105857_803/ckptdir/resume"
  total_iters: 800000
  ema_start: 1000
  N_rays_forward: null
  N_rays_grad: null
  N_samples_forward: null
  eikonal_reg: true
  sdf_reg: true
#  eikonal_reg: false
#  sdf_reg: false
  g_reg_every: 5
#  g_reg_every: -1 # path_reg false
  batch_gpu: 4
  warmup_iters: 20000
  cam_img_size: 32
  gen_img_size: 256 # train patch size
  data_img_size: 256
#  sample_mode: 'patch'
  lambda_pose: 0.
  fade_steps: 20000

train_r256_r64_ks1:
  base: train_base
  obs_training_dataset: *obs_carla_r256
  G_cfg:
    enable_decoder: true
#    freeze_renderer: true
#    renderer_detach: true
    freeze_renderer: false
    renderer_detach: false
    predict_rgb_residual: false
    renderer_cfg:
      N_layers_renderer: 2
      hidden_dim: 256
    decoder_cfg:
      upsample_list: [128, 256]
      kernel_size: 1
  G_kwargs:
    cam_cfg:
      img_size: 64
  D_cfg:
    pretrained_size: null
  D_renderer_cfg:
    pretrained_size: null
  init_renderer: true
  init_iters: 20000
  tl_finetune: false
#  finetune_dir: "../bucket_3690/results/StyleSDF-exp/train_cips3d_ffhq_v3/train_r64-20220411_105857_803/ckptdir/resume"
  total_iters: 800000
  ema_start: 1000
  N_rays_forward: null
  N_rays_grad: null
  N_samples_forward: null
  eikonal_reg: true
  sdf_reg: true
#  eikonal_reg: false
#  sdf_reg: false
  g_reg_every: 5
#  g_reg_every: -1 # path_reg false
  batch_gpu: 4
  warmup_iters: 20000
  cam_img_size: 64
  gen_img_size: 256 # train patch size
  data_img_size: 256
#  sample_mode: 'patch'
  lambda_pose: 0.
  fade_steps: 20000


train_r512_r64_ks1:
  base: train_base
  obs_training_dataset: *obs_carla_r512
  G_cfg:
    enable_decoder: true
#    freeze_renderer: true
#    renderer_detach: true
    freeze_renderer: false
    renderer_detach: false
    predict_rgb_residual: false
    renderer_cfg:
      N_layers_renderer: 2
      hidden_dim: 256
    decoder_cfg:
      upsample_list: [128, 256, 512]
      kernel_size: 1
  G_kwargs:
    cam_cfg:
      img_size: 64
  D_cfg:
    pretrained_size: null
  D_renderer_cfg:
    pretrained_size: null
  init_renderer: true
  init_iters: 20000
  tl_finetune: false
#  finetune_dir: "../bucket_3690/results/StyleSDF-exp/train_cips3d_ffhq_v3/train_r64-20220411_105857_803/ckptdir/resume"
  total_iters: 800000
  ema_start: 1000
  N_rays_forward: null
  N_rays_grad: null
  N_samples_forward: null
  eikonal_reg: true
  sdf_reg: true
#  eikonal_reg: false
#  sdf_reg: false
  g_reg_every: 5
#  g_reg_every: -1 # path_reg false
  batch_gpu: 4
  warmup_iters: 20000
  cam_img_size: 64
  gen_img_size: 512 # train patch size
  data_img_size: 512
#  sample_mode: 'patch'
  lambda_pose: 0.
  fade_steps: 20000


_gen_images:
  base: train_base
  network_pkl: "../bucket_3690/results/StyleSDF-exp/train_cips3d_ffhq/train_r64-20220402_160907_188/ckptdir/resume/G_ema.pth"
  N_gen_images_eval: 2048
  batch_gpu: 4

_setup_evaluation:
  base: train_base
  N_real_images_eval: 2048
  del_fid_real_images: true

eval_fid:
  base: train_r64
  network_pkl: "../bucket_3690/results/StyleSDF-exp/train_cips3d_ffhq_v2/train_r64-20220410_152640_400/ckptdir/resume/G_ema.pth"
  batch_gpu: 4
  N_gen_images_eval: 2048
  N_real_images_eval: 2048
  del_fid_real_images: true
  kid: false
  real_dir: null
  fake_dir: null
#  fake_dir: "../bucket_3690/results/StyleSDF-exp/train_cips3d_ffhq/train_r64-20220406_230105_974/exp/fid/fake"
  N_gen_images_eval_pre: 10


_render_video_web:
  root_obs: *root_obs
  port: 8501
  sidebar:
    sidebar_name: "show_video"
  model_cfg:
    register_modules:
      - exp.cips3d.models.render_video_web_v3
    name: exp.cips3d.models.render_video_web_v3.STModel
  mode:
    - _render_video_web
  _render_video_web:
    G_kwargs: *G_kwargs
    network_pkl: *network_pkl
    default_network_pkl: carla_r256_32_ks3
    N_frames: 40
    fps: 20
    hd_video: true
    view_mode:
      - circle
      - yaw
    default_view_mode: yaw
    seeds:
      - 123
    truncation_ratio: 0.5
    img_size: 32
    upsample_list: [128, 256, 512]
    N_samples: 128
    zero_noise_bufs: false
    light_location: [0.0, 3.0, 0]
  expname: ffhq1024x1024
  size: 1024
  identities: 4

_interpolate_z_web:
  root_obs: *root_obs
  port: 8501
  sidebar:
    sidebar_name: "show_video"
  model_cfg:
    register_modules:
      - exp.cips3d.models.render_video_web_v3
    name: exp.cips3d.models.render_video_web_v3.STModel
  mode:
    - _interpolate_z_web
  _interpolate_z_web:
    G_kwargs: *G_kwargs
    network_pkl: *network_pkl
    default_network_pkl: carla_r256_32_ks3
    N_samples: 5
    N_step: 20
    z_mode:
      - shape
      - app
      - style
    default_z_mode: shape
    interp_mode:
      - lerp
      - slerp
    azim: 0.
    elev: 0.8
    fov: 15.
    truncation_ratio: 0.5
    fps: 10
    hd_video: true
    seeds:
      - 123


eval_fid_r256:
  base: train_r256_r32_ks1
  network_pkl: "results/StyleSDF-exp/train_cips3d_carla_v3/train_r256_r32_ks1-20220421_155851_633/ckptdir/resume/G_ema.pth"
#  network_pkl: "results/StyleSDF-exp/train_cips3d_carla_v3/train_r256_r32_ks1-20220421_155851_633/ckptdir/best_fid/G_ema.pth"
#  network_pkl: "results/StyleSDF-exp/train_cips3d_carla_v3/train_r256_r32_ks1-20220421_160157_608/ckptdir/resume/G_ema.pth"
#  network_pkl: "results/StyleSDF-exp/train_cips3d_carla_v3/train_r256_r32_ks1-20220421_160157_608/ckptdir/best_fid/G_ema.pth"
  batch_gpu: 4
  N_gen_images_eval: 2048
  N_real_images_eval: 2048
  del_fid_real_images: true
  kid: false
  real_dir: "cache_pretrained/carla_r256_10112/"
#  real_dir: null
  fake_dir: null
#  fake_dir: "cache_pretrained/gen_carla_r256_5w_pigan"
  overwrite: false
  data_img_size: 256

_gen_images_carla:
  base: train_r256_r32_ks1
#  G_kwargs:
#    nerf_cfg:
#      'static_viewdirs': true
#    cam_cfg:
#      azim_range: 0
#      elev_range: 0
  network_pkl: *network_pkl
  default_network_pkl: "carla_r256_32_ks1_v1"
  N_gen_images_eval: 1000
  batch_gpu: 4
  truncation: 0.7

_style_mixing_web:
  root_obs: *root_obs
  port: 8501
  sidebar:
    sidebar_name: "show_video"
  model_cfg:
    register_modules:
      - exp.cips3d.models.render_video_web_v3
    name: exp.cips3d.models.render_video_web_v3.STModel
  mode:
    - _style_mixing_web
  _style_mixing_web:
    N_frames: 40
    fps: 20
    hd_video: true

    truncation_ratio: 0.7
    N_samples: 128
    zero_noise_bufs: false
    light_location: [ 0, 0, 5 ]
    show_trajectory: true

    seeds:
      - 123
    view_mode:
      - yaw
      - translate_rotate
      - circle
    default_view_mode: yaw
#    azim_range: [-1.57, 1.57]
#    azim_range: [-1., 1.]
    azim_range: [-3, 3]
    elev: 0.7
    trans_max: 0.06

    network_pkl: *network_pkl
    default_network_pkl: carla_r256_32_ks1_v1

    chunk: 1
    N_rows: 5
    N_cols: 5
    seed_list1:
      - 748265
#      - 912726
      - 902004
      - 372913
      - 362441
      - 566454

    seed_list2:
      - 169937
#      - 230201
      - 311680
      - 864386
      - 813373
      - 457183

_fixed_zs_multi_view_web:
  root_obs: *root_obs
  port: 8501
  sidebar:
    sidebar_name: "show_video"
  model_cfg:
    register_modules:
      - exp.cips3d.models.render_video_web_v3
    name: exp.cips3d.models.render_video_web_v3.STModel
  mode:
    - _fixed_zs_multi_view_web
  _fixed_zs_multi_view_web:
    N_frames: 40
    fps: 20
    hd_video: true

    truncation_ratio: 0.5
    N_samples: 128
    zero_noise_bufs: false
    light_location: [ 0, 0, 5 ]
    show_trajectory: true

    seeds:
      - 1010682
      - 4921831
#      - 8666477
#      - 5949945
#      - 5623520
#      - 2397456
#      - 2910468
#      - 1317869
    view_mode:
      - elev_circle
      - circle
    default_view_mode: elev_circle
#    azim_range: [-1.57, 1.57]
#    azim_range: [-1., 1.]
    azim_range: [-0.77, 0.77]
    elev: 0.
    trans_max: 0.06
    circle:
      azim_range: [0, 6.28]
      elev_range: 0.78
      fov_range: [15, 15]

    network_pkl: *network_pkl
    default_network_pkl: carla_r256_32_ks1_v1


